#!/usr/bin/env bash
# train concept model lr = 0.001 metric loss
CUDA_VISIBLE_DEVICES=3 python3 RobustnessAttacks/Hybrid_train.py -exp Concept_XtoC --seed 1 -log_dir models/VisualConceptReasoning/HybridConcept/CNN_Loss/Seed1/ -e 1000 -optimizer sgd -pretrained -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -b 64 -weight_decay 0.00004 -lr 0.001 -bottleneck -n_slots 2 -n_iters 3 -img_size 256 -scheduler Step -scheduler_step 100 -metric loss -bn_hidden_channels 2048
CUDA_VISIBLE_DEVICES=1 python3 RobustnessAttacks/Hybrid_train.py -exp Concept_XtoC --seed 2 -log_dir models/VisualConceptReasoning/HybridConcept/CNN_Loss/Seed2/ -e 1000 -optimizer sgd -pretrained -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -b 64 -weight_decay 0.00004 -lr 0.001 -bottleneck -n_slots 2 -n_iters 3 -img_size 256 -scheduler Step -scheduler_step 100 -metric loss -bn_hidden_channels 2048
CUDA_VISIBLE_DEVICES=2 python3 RobustnessAttacks/Hybrid_train.py -exp Concept_XtoC --seed 3 -log_dir models/VisualConceptReasoning/HybridConcept/CNN_LossCM/Seed3/ -e 1000 -optimizer sgd -pretrained -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -b 64 -weight_decay 0.00004 -lr 0.001 -bottleneck -n_slots 2 -n_iters 3 -img_size 256 -scheduler Step -scheduler_step 100 -metric loss -bn_hidden_channels 2048

# train concept model lr = 0.001 metric acc
CUDA_VISIBLE_DEVICES=1 python3 RobustnessAttacks/Hybrid_train.py -exp Concept_XtoC --seed 1 -log_dir models/VisualConceptReasoning/HybridConcept/CNN_Acc/Seed1/ -e 1000 -optimizer sgd -pretrained -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -b 64 -weight_decay 0.00004 -lr 0.001 -bottleneck -n_slots 2 -n_iters 3 -img_size 256 -scheduler Step -scheduler_step 100 -metric accuracy
CUDA_VISIBLE_DEVICES=2 python3 RobustnessAttacks/Hybrid_train.py -exp Concept_XtoC --seed 2 -log_dir models/VisualConceptReasoning/HybridConcept/CNN_Acc/Seed2/ -e 1000 -optimizer sgd -pretrained -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -b 64 -weight_decay 0.00004 -lr 0.001 -bottleneck -n_slots 2 -n_iters 3 -img_size 256 -scheduler Step -scheduler_step 100 -metric accuracy
CUDA_VISIBLE_DEVICES=0 python3 RobustnessAttacks/Hybrid_train.py -exp Concept_XtoC --seed 3 -log_dir models/VisualConceptReasoning/HybridConcept/CNN_Acc/Seed3/ -e 1000 -optimizer sgd -pretrained -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -b 64 -weight_decay 0.00004 -lr 0.001 -bottleneck -n_slots 2 -n_iters 3 -img_size 256 -scheduler Step -scheduler_step 100 -metric accuracy

# train independent end model with loss:
CUDA_VISIBLE_DEVICES=0 python3 RobustnessAttacks/Hybrid_train.py -exp Independent_CtoY --seed 1 -log_dir models/VisualConceptReasoning/HybridIndependent/Seed1/ -e 500 -optimizer sgd -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -metric loss
CUDA_VISIBLE_DEVICES=1 python3 RobustnessAttacks/Hybrid_train.py -exp Independent_CtoY --seed 2 -log_dir models/VisualConceptReasoning/HybridIndependent/Seed2/ -e 500 -optimizer sgd -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -metric loss
CUDA_VISIBLE_DEVICES=2 python3 RobustnessAttacks/Hybrid_train.py -exp Independent_CtoY --seed 3 -log_dir models/VisualConceptReasoning/HybridIndependent/Seed3/ -e 500 -optimizer sgd -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -metric loss

# train independent end model with acc:
CUDA_VISIBLE_DEVICES=0 python3 RobustnessAttacks/Hybrid_train.py -exp Independent_CtoY --seed 1 -log_dir models/VisualConceptReasoning/HybridIndependent/Seed1/ -e 500 -optimizer sgd -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -metric acc
CUDA_VISIBLE_DEVICES=1 python3 RobustnessAttacks/Hybrid_train.py -exp Independent_CtoY --seed 2 -log_dir models/VisualConceptReasoning/HybridIndependent/Seed2/ -e 500 -optimizer sgd -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -metric acc
CUDA_VISIBLE_DEVICES=2 python3 RobustnessAttacks/Hybrid_train.py -exp Independent_CtoY --seed 3 -log_dir models/VisualConceptReasoning/HybridIndependent/Seed3/ -e 500 -optimizer sgd -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -metric acc

# sequential training:
CUDA_VISIBLE_DEVICES=0 python3 RobustnessAttacks/Hybrid_train.py -exp Sequential_CtoY --seed 1 -log_dir models/VisualConceptReasoning/HybridSequential/Seed1/ -e 1000 -optimizer sgd -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -pretrained -n_attributes 112 -b 64 -weight_decay 0.00005 -lr 0.01 -metric loss -concept_model HybridConcept-CNN_Loss -binarize_attr
CUDA_VISIBLE_DEVICES=1 python3 RobustnessAttacks/Hybrid_train.py -exp Sequential_CtoY --seed 2 -log_dir models/VisualConceptReasoning/HybridSequential/Seed2/ -e 1000 -optimizer sgd -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -pretrained -n_attributes 112 -b 64 -weight_decay 0.00005 -lr 0.01 -metric loss -concept_model HybridConcept-CNN_Loss -binarize_attr
CUDA_VISIBLE_DEVICES=2 python3 RobustnessAttacks/Hybrid_train.py -exp Sequential_CtoY --seed 3 -log_dir models/VisualConceptReasoning/HybridSequential/Seed3/ -e 1000 -optimizer sgd -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -pretrained -n_attributes 112 -b 64 -weight_decay 0.00005 -lr 0.01 -metric loss -concept_model HybridConcept-CNN_Loss -binarize_attr

# train concept large model, lr = 0.001, metric loss
CUDA_VISIBLE_DEVICES=0 python3 RobustnessAttacks/Hybrid_train.py -exp Concept_XtoC_Large --seed 1 -log_dir models/VisualConceptReasoning/HybridConcept/CNNLarge_LossCM/Seed1/ -e 1000 -optimizer sgd -pretrained -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -b 64 -weight_decay 0.00004 -lr 0.001 -bottleneck -n_slots 2 -n_iters 3 -img_size 256 -scheduler Step -scheduler_step 100 -metric loss -bn_hidden_channels 2048
CUDA_VISIBLE_DEVICES=1 python3 RobustnessAttacks/Hybrid_train.py -exp Concept_XtoC_Large --seed 2 -log_dir models/VisualConceptReasoning/HybridConcept/CNNLarge_LossCM/Seed2/ -e 1000 -optimizer sgd -pretrained -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -b 64 -weight_decay 0.00004 -lr 0.001 -bottleneck -n_slots 2 -n_iters 3 -img_size 256 -scheduler Step -scheduler_step 100 -metric loss -bn_hidden_channels 256
CUDA_VISIBLE_DEVICES=2 python3 RobustnessAttacks/Hybrid_train.py -exp Concept_XtoC_Large --seed 3 -log_dir models/VisualConceptReasoning/HybridConcept/CNNLarge_LossCM/Seed3/ -e 1000 -optimizer sgd -pretrained -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -b 64 -weight_decay 0.00004 -lr 0.001 -bottleneck -n_slots 2 -n_iters 3 -img_size 256 -scheduler Step -scheduler_step 100 -metric loss -bn_hidden_channels 1024

# differently weighted loss function
CUDA_VISIBLE_DEVICES=2 python3 RobustnessAttacks/Hybrid_train.py -exp Concept_XtoC --seed 1 -log_dir models/VisualConceptReasoning/HybridConcept/LossCM2FN/CNN_LossCMFN/Seed1/ -e 1000 -optimizer sgd -pretrained -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -b 64 -weight_decay 0.00004 -lr 0.001 -bottleneck -n_slots 2 -n_iters 3 -img_size 256 -scheduler Step -scheduler_step 100 -metric loss -bn_hidden_channels 1024
CUDA_VISIBLE_DEVICES=3 python3 RobustnessAttacks/Hybrid_train.py -exp Concept_XtoC --seed 2 -log_dir models/VisualConceptReasoning/HybridConcept/LossCM2FN/CNN_LossCMFN/Seed2/ -e 1000 -optimizer sgd -pretrained -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -b 64 -weight_decay 0.00004 -lr 0.001 -bottleneck -n_slots 2 -n_iters 3 -img_size 256 -scheduler Step -scheduler_step 100 -metric loss -bn_hidden_channels 2048

# loss attempt 4, img_size 128 instead of 256
CUDA_VISIBLE_DEVICES=2 python3 RobustnessAttacks/Hybrid_train.py -exp Concept_XtoC_Large --seed 1 -log_dir models/VisualConceptReasoning/HybridConcept/LossCM2FN/CNNLarge_img_smallT/Seed1/ -e 1000 -optimizer sgd -pretrained -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -b 64 -weight_decay 0.00004 -lr 0.001 -bottleneck -n_slots 2 -n_iters 3 -img_size 128 -scheduler Step -scheduler_step 100 -metric loss -bn_hidden_channels 1024
CUDA_VISIBLE_DEVICES=3 python3 RobustnessAttacks/Hybrid_train.py -exp Concept_XtoC --seed 2 -log_dir models/VisualConceptReasoning/HybridConcept/LossCM2FN/CNN_img_smallT/Seed2/ -e 1000 -optimizer sgd -pretrained -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -b 64 -weight_decay 0.00004 -lr 0.001 -bottleneck -n_slots 2 -n_iters 3 -img_size 128 -scheduler Step -scheduler_step 100 -metric loss -bn_hidden_channels 2048

# loss attempt 4, img_size 128 instead of 256, attn_hidden_channels = 512 instead of 256
CUDA_VISIBLE_DEVICES=2 python3 RobustnessAttacks/Hybrid_train.py -exp Concept_XtoC_Large --seed 1 -log_dir models/VisualConceptReasoning/HybridConcept/LossCM2FN/CNNLarge_img_smallT_attnhid/Seed1/ -e 1000 -optimizer sgd -pretrained -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -b 64 -weight_decay 0.00004 -lr 0.001 -bottleneck -n_slots 2 -n_iters 3 -img_size 128 -scheduler Step -scheduler_step 100 -metric loss -bn_hidden_channels 1024 -attention_hidden_channels 512
CUDA_VISIBLE_DEVICES=3 python3 RobustnessAttacks/Hybrid_train.py -exp Concept_XtoC --seed 2 -log_dir models/VisualConceptReasoning/HybridConcept/LossCM2FN/CNN_img_smallT_attnhid/Seed2/ -e 1000 -optimizer sgd -pretrained -use_attr -data_dir data/CUB_200_2011/CUB_processed/class_attr_data_10 -n_attributes 112 -b 64 -weight_decay 0.00004 -lr 0.001 -bottleneck -n_slots 2 -n_iters 3 -img_size 128 -scheduler Step -scheduler_step 100 -metric loss -bn_hidden_channels 2048 -attention_hidden_channels 512